### PR TITLE
Switch to AliYun enterprise edition registry

### PR DESCRIPTION
**Pull request by AndiDog**

### CODE REVIEW

**Review by fiunchinho — APPROVED** [review]

**Comment by AndiDog** [comment]
@kubasobon can you take a look at the failed build https://app.circleci.com/pipelines/github/giantswarm/cluster-api-provider-aws/530/workflows/ff9f1579-8e46-4866-9686-aac5f0c9447b/jobs/510?

**Comment by kubasobon** [comment]
So the first time around it failed because "China": `net/http: TLS handshake timeout`
Shaky internet connection. However that's only for ARM, amd64 got pushed.

On the re-run however:
```
Login Succeeded
make ARCH=amd64 docker-push
make[1]: Entering directory '/home/circleci/project'
docker push giantswarm-registry.***********.cr.aliyuncs.com/giantswarm/cluster-api-aws-controller-amd64:cdcb9814aa7efc2449bead781257f5a51bf9815e
The push refers to repository [giantswarm-registry.***********.cr.aliyuncs.com/giantswarm/cluster-api-aws-controller-amd64]

0c2250f1: Preparing 
unknown: The requested tag already exists and cannot be overwritten.
```

**Comment by kubasobon** [comment]
I'll investigate if I can find a tag immutability setting in Aliyun

**Comment by AndiDog** [comment]
I removed the immutability settings. Adding a retry mechanism since the push intermittently fails. Let's see...

**Pull request merged**
